#!/bin/sh

DISABLE_COMPILE=1 uv run python pretrain.py \
    arch=trm \
    data_paths="[data/sudoku-extreme-1k-aug-1000-eval-10pct]" \
    evaluators="[]" \
    epochs=50000 \
    eval_interval=1000 \
    lr=1e-4 \
    puzzle_emb_lr=1e-4 \
    weight_decay=1.0 \
    puzzle_emb_weight_decay=1.0 \
    arch.H_layers=0 \
    arch.L_layers=2 \
    arch.H_cycles=3 \
    arch.L_cycles=6 \
    ema=True \
    arch.hidden_size=512 \
    arch.num_heads=8 \
    arch.expansion=4 \
    arch.forward_dtype=bfloat16 \
    global_batch_size=128 \
    arch.halt_exploration_prob=0.1 \
    arch.halt_max_steps=16 \
    +entity="jhunforspeed-soongsil-univ" \
    +project_name="totrm-sudoku-extreme" \
    
    # TRM에서의 값
    # arch=totrm \
    # data_paths="[data/sudoku-extreme-1k-aug-1000]" \
    # evaluators="[]" \
    # epochs=50000 \
    # eval_interval=5000 \
    # lr=1e-4 \
    # puzzle_emb_lr=1e-4 \
    # weight_decay=1.0 \
    # puzzle_emb_weight_decay=1.0 \
    # arch.H_layers=0 \
    # arch.L_layers=2 \
    # arch.H_cycles=3 \
    # arch.L_cycles=6 \
    # ema=True \
    # arch.hidden_size=512 \
    # arch.num_heads=8 \
    # arch.expansion=4 \
    # arch.forward_dtype=bfloat16 \
    # global_batch_size=768 \
    # arch.halt_exploration_prob=0.1 \
    # arch.halt_max_steps=16 \
    # +entity="jhunforspeed-soongsil-univ" \
    # +project_name="totrm" \
